Repository gitpod-io/workspace-images, pull requests merged in 2022-03, with the labels that each got.

#754 Ensure docker compose subcommand is available
  chunks/tool-docker/Dockerfile
  tests/tool-docker.yaml
Labels: team: workspace

#753 Promote date time stamped tags to Dockerhub
  .github/promote-images.yml
  .github/workflows/dockerhub-release.yml
  .github/workflows/push-main.yml
Labels: team: workspace

#756 Fix release image regression for dotnet
  .github/promote-images.yml
Labels: team: workspace

#757 Update readme with recent wflow changes
  CONTRIBUTING.md
Labels: team: workspace

#758 Add clippy to rust chunk
  chunks/lang-rust/Dockerfile
Labels: team: workspace

#761 Remove variants that are not being published
  chunks/lang-go/chunk.yaml
  chunks/lang-node/chunk.yaml
  chunks/lang-ruby/chunk.yaml
  chunks/tool-nix/chunk.yaml
  tests/lang-go.yaml
  tests/lang-node.yaml
  tests/lang-ruby.yaml
  tests/tool-nix.yaml
Labels: team: workspace

#471 feat: add chrome and electron support
  chunks/tool-chrome/Dockerfile
  dazzle.yaml
  tests/tool-chrome.yaml
Labels: community-contribution, team: workspace

#699 refactor(base/*-packages): Be completely Noninteractive and simplify apt wrappers
  base/Dockerfile
  base/install-packages
  base/upgrade-packages
Labels: team: workspace

#762 Update default branch name to `main`
  .github/workflows/lint.yml
  .github/workflows/push-main.yml
  CONTRIBUTING.md
Labels: team: workspace

#604 [initial commit] yugabytedb dedicated base image
  .github/promote-images.yml
  .github/sync-containers.yml
  chunks/tool-yugabytedb/Dockerfile
  dazzle.yaml
  tests/tool-yugabytedb.yaml
Labels: team: workspace

#764 Allow building specific chunks locally
  .gitignore
  .gitpod.Dockerfile
  .gitpod.yml
  CONTRIBUTING.md
  dazzle-up.sh
Labels: team: workspace

#771 Disable yugabyte image build temporarily
  .github/sync-containers.yml
  chunks/.tool-yugabytedb/Dockerfile
  dazzle.yaml
Labels: team: workspace

#772 Fix test that gets stuck
  chunks/lang-java/Dockerfile
Labels: team: workspace

#774 Run push-main w/o env approval
  .github/workflows/push-main.yml
Labels: team: workspace

#777 Use dedicated environment for dockerhub-release.yml workflow
  .github/workflows/dockerhub-release.yml
  .github/workflows/push-main.yml
Labels: team: workspace

#698 refactor: Gitpod config files
  .gitpod.Dockerfile
  .gitpod.yml
Labels: bug, team: workspace

#706 fix(tool-postgresql): Non-existent /workspace dir
  chunks/tool-postgresql/Dockerfile
  tests/tool-postgresql.yaml
Labels: team: workspace

#778 Update buildkit to v0.10.0
  .github/workflows/pull-request.yml
  .github/workflows/push-main.yml
  .gitpod.Dockerfile
Labels: team: workspace

#780 Delete unused workflow
  .github/workflows/image-promote.yml
Labels: team: workspace

#782 Upgrade to dazzle 0.1.10
  .github/workflows/pull-request.yml
  .github/workflows/push-main.yml
  .gitpod.Dockerfile
Labels: team: workspace

#783 fix: /usr/games missing PATH entry
  base/Dockerfile
Labels: team: workspace

#785 Log in again to extend GAR access_token
  .github/workflows/push-main.yml
Labels: team: workspace

#786 Use a unique ID to authenticate with Google again
  .github/workflows/push-main.yml
Labels: team: workspace

#700 feat: Use tigervnc and setup a proper desktop GUI developer env
  chunks/tool-vnc/.Xresources
  chunks/tool-vnc/.xinitrc
  chunks/tool-vnc/Dockerfile
  chunks/tool-vnc/gp-vncsession
  chunks/tool-vnc/start-vnc-session.sh
  tests/tool-vnc.yaml
Labels: enhancement, team: workspace

#787 Bump Go to 1.18
  chunks/lang-go/Dockerfile
  chunks/lang-go/chunk.yaml
  dazzle.yaml
  tests/lang-go.yaml
Labels: team: workspace

#788 Link to documentation for usage examples
  README.md
Labels: team: workspace
