Repository gitpod-io/workspace-images, pull requests merged in 2023-05, with the labels that each got.

#1084 [java] simplify Java 17 test
  tests/lang-java.yaml
Labels: team: workspace

#1085 Update workspace image deps
  .gitpod.Dockerfile
Labels: team: workspace, do-not-merge

#1087 Limit parallelism for skopeo copy / upload to GAR
  .github/workflows/push-main.yml
Labels: team: workspace

#1089 Update CODEOWNERS to include IDE team
  .github/CODEOWNERS
Labels: team: workspace

#1097 Add manual testing steps
  CONTRIBUTING.md
Labels: documentation
